name: relationship_app
description: İlişki analizi ve kişisel gelişim uygulaması

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7
  
  # State Management
  provider: ^6.0.5
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # Network
  http: ^1.1.0
  
  # Utils
  intl: ^0.18.1
  
  # File operations
  file_picker: ^6.1.1
  
  # Audio player for podcasts
  just_audio: ^0.9.35
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700